### ISSUE TITLE
bsc_mainnet | Take action /root/.ethereum/ is not Empty

### ISSUE THREAD

**Issue by steven4354** [maldo-ctrl/bsc-node-docker#1]
I ran into the below issue when running the node with `docker-compose up --build -d bsc_mainnet` 

<img width="729" alt="Screen Shot 2021-06-10 at 11 22 54 AM" src="https://user-images.githubusercontent.com/28765991/121577425-5ae7de80-c9de-11eb-8939-eaeb5c27b458.png">

I saw this response on this issue, but wasn't sure what the fix specifically was from their response: https://github.com/binance-chain/bsc/issues/276

**Comment by steven4354** [comment]
@maldo-ctrl actually I think I resolved this issue, I moved this repo over into my external drive and ran it inside the external drive instead and it seems to sync now. Going to try hooking it up to the liqudiation/venus repo and see if ti works :)

**Comment by steven4354** [comment]
actually a little early on the resolution, oops. i think this issue is popping up now:

<img width="1440" alt="Screen Shot 2021-06-10 at 8 37 01 PM" src="https://user-images.githubusercontent.com/28765991/121627175-bab8a680-ca2b-11eb-8b65-4693dd2eec50.png">

**Comment by steven4354** [comment]
i'm going to try running the full node from the binance docs and to compare and see if any differences and I'll push a pr if anything :)

**Comment by md0x** [comment]
Sorry to answer so late @steven4354.

I think it was working. That log you pointed out is normal: https://github.com/maldo-ctrl/bsc-node-docker/blob/28eb58bc0e6fedd621396b5c32119e073ebb5e9c/bootstrap.sh#L13 It's just checking if it needs to initialize the node folder or not.
